version: '3.9'

services:
  frontend:
    image: node:18-alpine
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://backend:3001
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - presentation-network

  backend:
    build:
      context: ./backend-python
    ports:
      - "3001:3001"
    env_file:
      - ./backend-python/.env
    restart: unless-stopped
    networks:
      - presentation-network
    volumes:
      - temp-data:/app/temp

networks:
  presentation-network:
    driver: bridge

volumes:
  temp-data:
