version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:3001
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - presentation-network

  backend:
    build:
      context: ./backend-python
    ports:
      - "3001:3001"
    env_file:
      - ./backend-python/.env
    restart: unless-stopped
    networks:
      - presentation-network
    volumes:
      - temp-data:/app/temp

networks:
  presentation-network:
    driver: bridge

volumes:
  temp-data:
