version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:3001
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build:
      context: ./backend-python
    ports:
      - "3001:3001"
    env_file:
      - ./backend-python/.env
    volumes:
      - ./backend-python:/app
